# Generated by Django 2.0.7 on 2018-07-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0005_auto_20180727_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
