# Generated by Django 2.0.7 on 2018-07-28 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_to_edge',
            old_name='node',
            new_name='edge',
        ),
    ]
