# Generated by Django 2.0.7 on 2018-07-28 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20180728_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment_to_node',
            name='node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_node', to='dictionary.Node'),
        ),
    ]
